databases:
  - name: postgres
    ipAllowList: []
    plan: free

services:
  - type: web
    name: hello_app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: hello-app
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
