databases:
  - name: mysite
    ipAllowList: []
    plan: free

services:
  - type: web
    name: hello_world_RoR
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hello_world_RoR
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
